"""renomear criador_em para criado_em

Revision ID: 1a7fc92da538
Revises: e536de4a7d35
Create Date: 2026-03-10 19:30:57.859583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7fc92da538'
down_revision = 'e536de4a7d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.drop_column('criador_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criador_em', sa.DATETIME(), nullable=True))
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
