"""tabela licenca

Revision ID: 20221d5c694b
Revises: e8a475ed85d0
Create Date: 2026-03-03 22:17:48.253639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20221d5c694b'
down_revision = 'e8a475ed85d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('plano', sa.String(length=30), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licencas')
    # ### end Alembic commands ###
