"""white-label empresa

Revision ID: 44699e242725
Revises: 1a7fc92da538
Create Date: 2026-03-24 19:13:28.993081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44699e242725'
down_revision = '1a7fc92da538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wl_nome_sistema', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wl_cor_primaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('wl_cor_secundaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('wl_logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wl_dominio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wl_suporte_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('wl_suporte_fone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('wl_rodape_texto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('wl_rodape_texto')
        batch_op.drop_column('wl_suporte_fone')
        batch_op.drop_column('wl_suporte_email')
        batch_op.drop_column('wl_dominio')
        batch_op.drop_column('wl_logo_url')
        batch_op.drop_column('wl_cor_secundaria')
        batch_op.drop_column('wl_cor_primaria')
        batch_op.drop_column('wl_nome_sistema')

    # ### end Alembic commands ###
