"""empresa motoboy formas_pagamento financeiro

Revision ID: e536de4a7d35
Revises: 2560c0dcf633
Create Date: 2026-03-09 22:48:53.300905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e536de4a7d35'
down_revision = '2560c0dcf633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_febraban', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('taxa_por_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    if_not_exists=True
    )
    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('taxa_operadora_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dias_para_recebimento', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    if_not_exists=True
    )
    op.create_table('motoboy_detalhes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=True),
    sa.Column('modelo_veiculo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('user_id'),
    if_not_exists=True
    )
    op.create_table('transacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('favorecido_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['favorecido_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motoboy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distancia_km', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('taxa_entrega_cobrada', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_repasse_motoboy', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key('fk_pedidos_motoboy_id', 'users', ['motoboy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('valor_repasse_motoboy')
        batch_op.drop_column('taxa_entrega_cobrada')
        batch_op.drop_column('distancia_km')
        batch_op.drop_column('motoboy_id')

    op.drop_table('transacoes_financeiras')
    op.drop_table('motoboy_detalhes')
    op.drop_table('fornecedores')
    op.drop_table('formas_pagamento')
    op.drop_table('empresas')
    op.drop_table('bancos')
    # ### end Alembic commands ###
